apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  {{- range $name, $data := .Values.config }}
  {{ $name }}: |
    {{- (tpl $data $) | nindent 4 }}
  {{- end }}
