name: release
on: 
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  release:
    types: [published, created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.0
        with:
          charts_dir: charts
          charts_repo_url: https://osgp.github.io/charts/
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
